product_types:
  - id: 1
    name: "Electronics"
    description: "Electronic devices"
    metadata_schema:
      warranty: "integer"
      brand: "string"
      battery_life: "integer"
      screen_size: "float"
      camera_quality: "integer"
      processor_speed: "float"

  - id: 2
    name: "Clothing"
    description: "Apparel"
    metadata_schema:
      size: "string"
      color: "string"
      material: "string"
      fit: "string"
      washability: "integer"

products:
  - id: 1
    product_type_id: 1
    user_id: admin1
    name: "Smartphone X"
    brand: "BrandX"
    price: 799
    score: 4.6
    image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAflBMVEX///8AAAArKyuDg4MnJyd7e3vX19fT09Pq6ura2tre3t4ZGRkODg74+PgEBAQKCgqMjIwjIyPz8/MbGxtFRUXm5uYwMDA4ODipqam8vLySkpJNTU0+Pj5ycnKampqkpKRdXV1hYWHAwMCzs7NqamrHx8efn59gYGBXV1dJSUmwINnuAAAEu0lEQVR4nO2cbXeqOhBGG0XxDUWqVavYCtbW//8H77WViEBqwgwh55xnf+taXSFbIEySyTw9AQAAAAAAAAAAAAAAAAAAAADAv42/Drs9i3TDtc9vsXmfiBaYfCa8Gi9tWPyw2rBpRF/taVx4j3g8hvN2PYTwRhwe/XHbHkKMh3SP5XPbFhfmA7LIom2HH85Uj32+tYnXsYh3N+CfaB7RrbFJr0/9VUzx45m8/DggNRXKhhZLpt4ZsdzJDrySGvKyZra0H6Q2gXxHO5Rm/KyVOdM3yZxIjpqUIfg1a2TN1jFjTlkf9oRGDtmbxtYtc4JsvDkSGsletS+2btVgmw03hDayoLfH1qsaxNdOrAhtZINWl61XNegxDFsQ4QQiOSDCCURyQIQTiOSACCeWRQbJep3QF20qsCmy7F7/s9Pld7EnEvSmQjLrcs/urYksC0v1K+b1Flsio9Ka6pzXxJJI5BU9hHhhfbosiRzLHkLEhGuWsCPSr/IQU5YNjSt2RA6VIqSlmyJWRALFFinnQpgVkY9qDyEYN5atiOxVIm+EqxawItJViYSEqxaASI6HIq8qEcrSeQErIqlKhDHzwopINK32mDIGKXY+iIrd663RZYJhkqaJr5jK2BFRPFv6iTCD06cMO8fnsOL7Yylo3JUtDPZk0nPx2fTC4o2xJNKfiRITzZjxrWIK8P8cM75XsTWxSkvv+zTVatxfVWl8/xB3aQ7Wprrrwj2Z6XmEigHvm23upthbfPDvJu0rrUyP4EEyW+c2Xba5HHSSKiu9aDGqHCPyeNLE7gLdcB+/f8Ynzbc8Ur4eN2SyhcNLpgOtXM/sEXVXRM/DfZFlR8vDeZFl5VfwzxMZaSffui0y1E9adVrEJInYZRHfJBnaYRHf6MRDSyLRJowPh3j/y8rch9nJjVZE0q2MZcdHRdSYGJ5AaUEkKXyq36t2ejYVMzC3RIK41IdJeUqSmnpIkWwR8KVhkahyIaW40lieR2qLbK5/U7YqdLbeFBH5fT7n2txDilzXN3QXAmqKqCPZ/PZbHY+byOCSMDv/IHg8Fhn8EsneTGp5iNzgN0xJGo9Ffo9ks4f6rZaH4Dzl8UDkUSR7pHhYFHkckX/1nyLlFoozIloRec27YVPEKJJ1WMQsknVXxDCSdVbEgocVkcQ4AnRTxDgid1SkRiTrpEi9yIkkEvSJOZ9VInUjjvoiweWk64KUAlYhokyjaU7kZ0/omXJTyiLKnI3mRLJUKsrRu5JIqLpqgyJZ1Ml5fG9o0aPRVRRfdVGIQAQiEIEIRCACEYhABCKuilSfqGqIrFZQEyKqVPgmmGXp9Y1sTx/sichN3EZEdLIqedjJQljNJAwErwsb9ecW+9u5DQ6Rv6YI0l9TlupwbYNYko8ES6Ewua7IeKzQFJbSbQ4U0xvIPVdSPVOZoXFuvbwhJcspv2a9a6Xg5Oj23aIVnIxum+mzuIEK1b/DWAL0fjtkNvcsMr/bqSQPN2fhBGYHG6sYtF5I+oLHUDdm6EAp6WeWGhIjzfMezdFhGjGjQ7seR76vcfLwkFpz7IjpjAU+jq1UK38+8mp8M0r3Ydci4T7lrBMDAAAAAAAAAAAAAAAAAAAAAAB/Iv8BOsFRVwkkrQYAAAAASUVORK5CYII="


  - id: 2
    product_type_id: 2
    user_id: admin1
    name: "Premium T-Shirt"
    brand: "FashionFit"
    price: 49
    score: 4.3
    image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAflBMVEX///8AAAArKyuDg4MnJyd7e3vX19fT09Pq6ura2tre3t4ZGRkODg74+PgEBAQKCgqMjIwjIyPz8/MbGxtFRUXm5uYwMDA4ODipqam8vLySkpJNTU0+Pj5ycnKampqkpKRdXV1hYWHAwMCzs7NqamrHx8efn59gYGBXV1dJSUmwINnuAAAEu0lEQVR4nO2cbXeqOhBGG0XxDUWqVavYCtbW//8H77WViEBqwgwh55xnf+taXSFbIEySyTw9AQAAAAAAAAAAAAAAAAAAAADAv42/Drs9i3TDtc9vsXmfiBaYfCa8Gi9tWPyw2rBpRF/taVx4j3g8hvN2PYTwRhwe/XHbHkKMh3SP5XPbFhfmA7LIom2HH85Uj32+tYnXsYh3N+CfaB7RrbFJr0/9VUzx45m8/DggNRXKhhZLpt4ZsdzJDrySGvKyZra0H6Q2gXxHO5Rm/KyVOdM3yZxIjpqUIfg1a2TN1jFjTlkf9oRGDtmbxtYtc4JsvDkSGsletS+2btVgmw03hDayoLfH1qsaxNdOrAhtZINWl61XNegxDFsQ4QQiOSDCCURyQIQTiOSACCeWRQbJep3QF20qsCmy7F7/s9Pld7EnEvSmQjLrcs/urYksC0v1K+b1Flsio9Ka6pzXxJJI5BU9hHhhfbosiRzLHkLEhGuWsCPSr/IQU5YNjSt2RA6VIqSlmyJWRALFFinnQpgVkY9qDyEYN5atiOxVIm+EqxawItJViYSEqxaASI6HIq8qEcrSeQErIqlKhDHzwopINK32mDIGKXY+iIrd663RZYJhkqaJr5jK2BFRPFv6iTCD06cMO8fnsOL7Yylo3JUtDPZk0nPx2fTC4o2xJNKfiRITzZjxrWIK8P8cM75XsTWxSkvv+zTVatxfVWl8/xB3aQ7Wprrrwj2Z6XmEigHvm23upthbfPDvJu0rrUyP4EEyW+c2Xba5HHSSKiu9aDGqHCPyeNLE7gLdcB+/f8Ynzbc8Ur4eN2SyhcNLpgOtXM/sEXVXRM/DfZFlR8vDeZFl5VfwzxMZaSffui0y1E9adVrEJInYZRHfJBnaYRHf6MRDSyLRJowPh3j/y8rch9nJjVZE0q2MZcdHRdSYGJ5AaUEkKXyq36t2ejYVMzC3RIK41IdJeUqSmnpIkWwR8KVhkahyIaW40lieR2qLbK5/U7YqdLbeFBH5fT7n2txDilzXN3QXAmqKqCPZ/PZbHY+byOCSMDv/IHg8Fhn8EsneTGp5iNzgN0xJGo9Ffo9ks4f6rZaH4Dzl8UDkUSR7pHhYFHkckX/1nyLlFoozIloRec27YVPEKJJ1WMQsknVXxDCSdVbEgocVkcQ4AnRTxDgid1SkRiTrpEi9yIkkEvSJOZ9VInUjjvoiweWk64KUAlYhokyjaU7kZ0/omXJTyiLKnI3mRLJUKsrRu5JIqLpqgyJZ1Ml5fG9o0aPRVRRfdVGIQAQiEIEIRCACEYhABCKuilSfqGqIrFZQEyKqVPgmmGXp9Y1sTx/sichN3EZEdLIqedjJQljNJAwErwsb9ecW+9u5DQ6Rv6YI0l9TlupwbYNYko8ES6Ewua7IeKzQFJbSbQ4U0xvIPVdSPVOZoXFuvbwhJcspv2a9a6Xg5Oj23aIVnIxum+mzuIEK1b/DWAL0fjtkNvcsMr/bqSQPN2fhBGYHG6sYtF5I+oLHUDdm6EAp6WeWGhIjzfMezdFhGjGjQ7seR76vcfLwkFpz7IjpjAU+jq1UK38+8mp8M0r3Ydci4T7lrBMDAAAAAAAAAAAAAAAAAAAAAAB/Iv8BOsFRVwkkrQYAAAAASUVORK5CYII="


  - id: 3
    product_type_id: 1
    user_id: admin1
    name: "Smartphone Z"
    brand: "BrandY"
    price: 899
    score: 4.4
    image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAflBMVEX///8AAAArKyuDg4MnJyd7e3vX19fT09Pq6ura2tre3t4ZGRkODg74+PgEBAQKCgqMjIwjIyPz8/MbGxtFRUXm5uYwMDA4ODipqam8vLySkpJNTU0+Pj5ycnKampqkpKRdXV1hYWHAwMCzs7NqamrHx8efn59gYGBXV1dJSUmwINnuAAAEu0lEQVR4nO2cbXeqOhBGG0XxDUWqVavYCtbW//8H77WViEBqwgwh55xnf+taXSFbIEySyTw9AQAAAAAAAAAAAAAAAAAAAADAv42/Drs9i3TDtc9vsXmfiBaYfCa8Gi9tWPyw2rBpRF/taVx4j3g8hvN2PYTwRhwe/XHbHkKMh3SP5XPbFhfmA7LIom2HH85Uj32+tYnXsYh3N+CfaB7RrbFJr0/9VUzx45m8/DggNRXKhhZLpt4ZsdzJDrySGvKyZra0H6Q2gXxHO5Rm/KyVOdM3yZxIjpqUIfg1a2TN1jFjTlkf9oRGDtmbxtYtc4JsvDkSGsletS+2btVgmw03hDayoLfH1qsaxNdOrAhtZINWl61XNegxDFsQ4QQiOSDCCURyQIQTiOSACCeWRQbJep3QF20qsCmy7F7/s9Pld7EnEvSmQjLrcs/urYksC0v1K+b1Flsio9Ka6pzXxJJI5BU9hHhhfbosiRzLHkLEhGuWsCPSr/IQU5YNjSt2RA6VIqSlmyJWRALFFinnQpgVkY9qDyEYN5atiOxVIm+EqxawItJViYSEqxaASI6HIq8qEcrSeQErIqlKhDHzwopINK32mDIGKXY+iIrd663RZYJhkqaJr5jK2BFRPFv6iTCD06cMO8fnsOL7Yylo3JUtDPZk0nPx2fTC4o2xJNKfiRITzZjxrWIK8P8cM75XsTWxSkvv+zTVatxfVWl8/xB3aQ7Wprrrwj2Z6XmEigHvm23upthbfPDvJu0rrUyP4EEyW+c2Xba5HHSSKiu9aDGqHCPyeNLE7gLdcB+/f8Ynzbc8Ur4eN2SyhcNLpgOtXM/sEXVXRM/DfZFlR8vDeZFl5VfwzxMZaSffui0y1E9adVrEJInYZRHfJBnaYRHf6MRDSyLRJowPh3j/y8rch9nJjVZE0q2MZcdHRdSYGJ5AaUEkKXyq36t2ejYVMzC3RIK41IdJeUqSmnpIkWwR8KVhkahyIaW40lieR2qLbK5/U7YqdLbeFBH5fT7n2txDilzXN3QXAmqKqCPZ/PZbHY+byOCSMDv/IHg8Fhn8EsneTGp5iNzgN0xJGo9Ffo9ks4f6rZaH4Dzl8UDkUSR7pHhYFHkckX/1nyLlFoozIloRec27YVPEKJJ1WMQsknVXxDCSdVbEgocVkcQ4AnRTxDgid1SkRiTrpEi9yIkkEvSJOZ9VInUjjvoiweWk64KUAlYhokyjaU7kZ0/omXJTyiLKnI3mRLJUKsrRu5JIqLpqgyJZ1Ml5fG9o0aPRVRRfdVGIQAQiEIEIRCACEYhABCKuilSfqGqIrFZQEyKqVPgmmGXp9Y1sTx/sichN3EZEdLIqedjJQljNJAwErwsb9ecW+9u5DQ6Rv6YI0l9TlupwbYNYko8ES6Ewua7IeKzQFJbSbQ4U0xvIPVdSPVOZoXFuvbwhJcspv2a9a6Xg5Oj23aIVnIxum+mzuIEK1b/DWAL0fjtkNvcsMr/bqSQPN2fhBGYHG6sYtF5I+oLHUDdm6EAp6WeWGhIjzfMezdFhGjGjQ7seR76vcfLwkFpz7IjpjAU+jq1UK38+8mp8M0r3Ydci4T7lrBMDAAAAAAAAAAAAAAAAAAAAAAB/Iv8BOsFRVwkkrQYAAAAASUVORK5CYII="


  - id: 4
    product_type_id: 2
    user_id: admin1
    name: "Casual T-Shirt"
    brand: "UrbanStyle"
    price: 35
    score: 4.2
    image: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAMAAACahl6sAAAAflBMVEX///8AAAArKyuDg4MnJyd7e3vX19fT09Pq6ura2tre3t4ZGRkODg74+PgEBAQKCgqMjIwjIyPz8/MbGxtFRUXm5uYwMDA4ODipqam8vLySkpJNTU0+Pj5ycnKampqkpKRdXV1hYWHAwMCzs7NqamrHx8efn59gYGBXV1dJSUmwINnuAAAEu0lEQVR4nO2cbXeqOhBGG0XxDUWqVavYCtbW//8H77WViEBqwgwh55xnf+taXSFbIEySyTw9AQAAAAAAAAAAAAAAAAAAAADAv42/Drs9i3TDtc9vsXmfiBaYfCa8Gi9tWPyw2rBpRF/taVx4j3g8hvN2PYTwRhwe/XHbHkKMh3SP5XPbFhfmA7LIom2HH85Uj32+tYnXsYh3N+CfaB7RrbFJr0/9VUzx45m8/DggNRXKhhZLpt4ZsdzJDrySGvKyZra0H6Q2gXxHO5Rm/KyVOdM3yZxIjpqUIfg1a2TN1jFjTlkf9oRGDtmbxtYtc4JsvDkSGsletS+2btVgmw03hDayoLfH1qsaxNdOrAhtZINWl61XNegxDFsQ4QQiOSDCCURyQIQTiOSACCeWRQbJep3QF20qsCmy7F7/s9Pld7EnEvSmQjLrcs/urYksC0v1K+b1Flsio9Ka6pzXxJJI5BU9hHhhfbosiRzLHkLEhGuWsCPSr/IQU5YNjSt2RA6VIqSlmyJWRALFFinnQpgVkY9qDyEYN5atiOxVIm+EqxawItJViYSEqxaASI6HIq8qEcrSeQErIqlKhDHzwopINK32mDIGKXY+iIrd663RZYJhkqaJr5jK2BFRPFv6iTCD06cMO8fnsOL7Yylo3JUtDPZk0nPx2fTC4o2xJNKfiRITzZjxrWIK8P8cM75XsTWxSkvv+zTVatxfVWl8/xB3aQ7Wprrrwj2Z6XmEigHvm23upthbfPDvJu0rrUyP4EEyW+c2Xba5HHSSKiu9aDGqHCPyeNLE7gLdcB+/f8Ynzbc8Ur4eN2SyhcNLpgOtXM/sEXVXRM/DfZFlR8vDeZFl5VfwzxMZaSffui0y1E9adVrEJInYZRHfJBnaYRHf6MRDSyLRJowPh3j/y8rch9nJjVZE0q2MZcdHRdSYGJ5AaUEkKXyq36t2ejYVMzC3RIK41IdJeUqSmnpIkWwR8KVhkahyIaW40lieR2qLbK5/U7YqdLbeFBH5fT7n2txDilzXN3QXAmqKqCPZ/PZbHY+byOCSMDv/IHg8Fhn8EsneTGp5iNzgN0xJGo9Ffo9ks4f6rZaH4Dzl8UDkUSR7pHhYFHkckX/1nyLlFoozIloRec27YVPEKJJ1WMQsknVXxDCSdVbEgocVkcQ4AnRTxDgid1SkRiTrpEi9yIkkEvSJOZ9VInUjjvoiweWk64KUAlYhokyjaU7kZ0/omXJTyiLKnI3mRLJUKsrRu5JIqLpqgyJZ1Ml5fG9o0aPRVRRfdVGIQAQiEIEIRCACEYhABCKuilSfqGqIrFZQEyKqVPgmmGXp9Y1sTx/sichN3EZEdLIqedjJQljNJAwErwsb9ecW+9u5DQ6Rv6YI0l9TlupwbYNYko8ES6Ewua7IeKzQFJbSbQ4U0xvIPVdSPVOZoXFuvbwhJcspv2a9a6Xg5Oj23aIVnIxum+mzuIEK1b/DWAL0fjtkNvcsMr/bqSQPN2fhBGYHG6sYtF5I+oLHUDdm6EAp6WeWGhIjzfMezdFhGjGjQ7seR76vcfLwkFpz7IjpjAU+jq1UK38+8mp8M0r3Ydci4T7lrBMDAAAAAAAAAAAAAAAAAAAAAAB/Iv8BOsFRVwkkrQYAAAAASUVORK5CYII="


product_metadata:
  - id: 1
    product_id: 1
    attribute: "warranty"
    value: "24"
    score: 4.8
  - id: 2
    product_id: 1
    attribute: "battery_life"
    value: "18"
    score: 4.5
  - id: 3
    product_id: 1
    attribute: "screen_size"
    value: "6.5"
    score: 4.7
  - id: 4
    product_id: 1
    attribute: "camera_quality"
    value: "108"
    score: 4.6
  - id: 5
    product_id: 1
    attribute: "processor_speed"
    value: "3.2"
    score: 4.8

  - id: 6
    product_id: 2
    attribute: "size"
    value: "L"
    score: 4.2
  - id: 7
    product_id: 2
    attribute: "color"
    value: "Black"
    score: 4.5
  - id: 8
    product_id: 2
    attribute: "material"
    value: "Cotton"
    score: 4.6
  - id: 9
    product_id: 2
    attribute: "fit"
    value: "Slim"
    score: 4.3
  - id: 10
    product_id: 2
    attribute: "washability"
    value: "10"
    score: 4.2

  - id: 11
    product_id: 3
    attribute: "warranty"
    value: "20"
    score: 4.4
  - id: 12
    product_id: 3
    attribute: "battery_life"
    value: "22"
    score: 4.7
  - id: 13
    product_id: 3
    attribute: "screen_size"
    value: "6.8"
    score: 4.6
  - id: 14
    product_id: 3
    attribute: "camera_quality"
    value: "120"
    score: 4.8
  - id: 15
    product_id: 3
    attribute: "processor_speed"
    value: "3.5"
    score: 4.9

  - id: 16
    product_id: 4
    attribute: "size"
    value: "M"
    score: 4.3
  - id: 17
    product_id: 4
    attribute: "color"
    value: "White"
    score: 4.4
  - id: 18
    product_id: 4
    attribute: "material"
    value: "Polyester"
    score: 4.1
  - id: 19
    product_id: 4
    attribute: "fit"
    value: "Regular"
    score: 4.2
  - id: 20
    product_id: 4
    attribute: "washability"
    value: "8"
    score: 4.0