product_types:
  - id: 1
    name: "Electronics"
    description: "Electronic devices"
    metadata_schema:
      warranty: "integer"
      brand: "string"
  - id: 2
    name: "Clothing"
    description: "Apparel"
    metadata_schema:
      size: "string"
      color: "string"


products:
  - id: 1
    product_type_id: 1
    user_id: 1
    name: "Smartphone"
    image: "smartphone.png"
    brand: "BrandX"
    score: 4.5
  - id: 2
    product_type_id: 2
    user_id: 1
    name: "T-Shirt"
    image: "tshirt.png"
    brand: "BrandY"
    score: 4.0
  - id: 3
    product_type_id: 1
    user_id: 1
    name: "Smartphone 2"
    image: "smartphone.png"
    brand: "BrandX"
    score: 4.3
  - id: 4
    product_type_id: 2
    user_id: 1
    name: "T-Shirt 2"
    image: "tshirt.png"
    brand: "BrandY"
    score: 4.2


product_metadata:
  - id: 1
    product_id: 1
    attribute: "warranty"
    value: "24"
    score: 4.8
  - id: 2
    product_id: 2
    attribute: "size"
    value: "L"
    score: 4.2
  - id: 3
    product_id: 3
    attribute: "warranty"
    value: "20"
    score: 4.4
  - id: 4
    product_id: 4
    attribute: "size"
    value: "M"
    score: 4.3