product_types:
  - id: 1
    name: "Electronics"
    description: "Electronic devices"
    metadata_schema:
      warranty: "integer"
      brand: "string"
  - id: 2
    name: "Clothing"
    description: "Apparel"
    metadata_schema:
      size: "string"
      color: "string"


products:
  - id: 1
    id_product_type: 1
    id_user: 1
    name: "Smartphone"
    image: "smartphone.png"
    brand: "BrandX"
    score: 4.5
  - id: 2
    id_product_type: 2
    id_user: 1
    name: "T-Shirt"
    image: "tshirt.png"
    brand: "BrandY"
    score: 4.0


product_metadata:
  - id: 1
    id_product: 1
    attribute: "warranty"
    value: "24"
    score: 4.8
  - id: 2
    id_product: 2
    attribute: "size"
    value: "L"
    score: 4.2